name: 'GitWit Action'
description: 'Run GitWit lint or changelog'

inputs:
  command:
    description: 'Command to run (lint or changelog)'
    required: true
  args:
    description: 'Additional arguments'
    required: false

runs:
  using: 'docker'
  image: 'docker://ghcr.io/rafandoo/gitwit-action:v1'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.args }}

branding:
  icon: 'check-circle'
  color: 'blue'
